POST {{local}}/api/login
Content-Type: application/x-www-form-urlencoded

avatar = https://github-content/sha/avatar.png &
email = nicho@gmail.com &
type = 2 &
name = nico &
open_id = 12

###

###
GET {{local}}/api/test
Accept: application/json


### Get Contact
GET {{local}}/api/contact?user_token=9a167953ca146b0a410efa541a584ad9
Accept: application/json
Authorization: Bearer 575c6580f21d683364f659aca554b739


### Get RTC Token
GET {{local}}/api/get_rtc_token
Accept: application/json
